// Code generated by protoc-gen-go. DO NOT EDIT.
// source: article.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Article struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string               `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_4523cf6ed8cd7f5d, []int{0}
}
func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (dst *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(dst, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Article) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Article) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Article) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type ArticleServiceCreateRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleServiceCreateRequest) Reset()         { *m = ArticleServiceCreateRequest{} }
func (m *ArticleServiceCreateRequest) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceCreateRequest) ProtoMessage()    {}
func (*ArticleServiceCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_4523cf6ed8cd7f5d, []int{1}
}
func (m *ArticleServiceCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceCreateRequest.Unmarshal(m, b)
}
func (m *ArticleServiceCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceCreateRequest.Marshal(b, m, deterministic)
}
func (dst *ArticleServiceCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceCreateRequest.Merge(dst, src)
}
func (m *ArticleServiceCreateRequest) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceCreateRequest.Size(m)
}
func (m *ArticleServiceCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceCreateRequest proto.InternalMessageInfo

func (m *ArticleServiceCreateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ArticleServiceCreateRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type ArticleServiceCreateResponsee struct {
	Article              *Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleServiceCreateResponsee) Reset()         { *m = ArticleServiceCreateResponsee{} }
func (m *ArticleServiceCreateResponsee) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceCreateResponsee) ProtoMessage()    {}
func (*ArticleServiceCreateResponsee) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_4523cf6ed8cd7f5d, []int{2}
}
func (m *ArticleServiceCreateResponsee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceCreateResponsee.Unmarshal(m, b)
}
func (m *ArticleServiceCreateResponsee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceCreateResponsee.Marshal(b, m, deterministic)
}
func (dst *ArticleServiceCreateResponsee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceCreateResponsee.Merge(dst, src)
}
func (m *ArticleServiceCreateResponsee) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceCreateResponsee.Size(m)
}
func (m *ArticleServiceCreateResponsee) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceCreateResponsee.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceCreateResponsee proto.InternalMessageInfo

func (m *ArticleServiceCreateResponsee) GetArticle() *Article {
	if m != nil {
		return m.Article
	}
	return nil
}

func init() {
	proto.RegisterType((*Article)(nil), "article.Article")
	proto.RegisterType((*ArticleServiceCreateRequest)(nil), "article.ArticleServiceCreateRequest")
	proto.RegisterType((*ArticleServiceCreateResponsee)(nil), "article.ArticleServiceCreateResponsee")
}

func init() { proto.RegisterFile("article.proto", fileDescriptor_article_4523cf6ed8cd7f5d) }

var fileDescriptor_article_4523cf6ed8cd7f5d = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0xc9, 0xda, 0x0f, 0x3a, 0xc5, 0x22, 0x8b, 0x87, 0x10, 0x11, 0x4b, 0x10, 0x29, 0x1e,
	0xb6, 0x10, 0x4f, 0x1e, 0xa3, 0x07, 0x0f, 0xde, 0xa2, 0x78, 0xf0, 0x22, 0x49, 0x76, 0xac, 0x0b,
	0xa9, 0xbb, 0x26, 0x13, 0xc1, 0x9f, 0xe6, 0xbf, 0x13, 0xf7, 0x83, 0xa2, 0x04, 0x7a, 0xdb, 0x1d,
	0x9e, 0xf7, 0x9d, 0x87, 0x81, 0xc3, 0xb2, 0x25, 0x55, 0x37, 0x28, 0x4c, 0xab, 0x49, 0xf3, 0xa9,
	0xff, 0x26, 0x67, 0x1b, 0xad, 0x37, 0x0d, 0xae, 0xed, 0xb8, 0xea, 0x5f, 0xd7, 0xa4, 0xb6, 0xd8,
	0x51, 0xb9, 0x35, 0x8e, 0x4c, 0xbf, 0x23, 0x98, 0xe6, 0x0e, 0xe6, 0x0b, 0x60, 0x4a, 0xc6, 0xd1,
	0x32, 0x5a, 0xcd, 0x0a, 0xa6, 0x24, 0x3f, 0x86, 0x31, 0x29, 0x6a, 0x30, 0x66, 0x76, 0xe4, 0x3e,
	0x9c, 0xc3, 0xa8, 0xd2, 0xf2, 0x2b, 0x3e, 0xb0, 0x43, 0xfb, 0xe6, 0xd7, 0x00, 0x75, 0x8b, 0x25,
	0xa1, 0x7c, 0x29, 0x29, 0x1e, 0x2d, 0xa3, 0xd5, 0x3c, 0x4b, 0x84, 0xdb, 0x2d, 0xc2, 0x6e, 0xf1,
	0x18, 0x76, 0x17, 0x33, 0x4f, 0xe7, 0xf4, 0x1b, 0xed, 0x8d, 0x0c, 0xd1, 0xf1, 0xfe, 0xa8, 0xa7,
	0x73, 0x4a, 0xef, 0xe0, 0xc4, 0xab, 0x3f, 0x60, 0xfb, 0xa9, 0x6a, 0xbc, 0xb5, 0xad, 0x05, 0x7e,
	0xf4, 0xd8, 0xd1, 0x4e, 0x3f, 0x1a, 0xd2, 0x67, 0x3b, 0xfd, 0xf4, 0x1e, 0x4e, 0x87, 0x8b, 0x3a,
	0xa3, 0xdf, 0x3b, 0x44, 0x7e, 0x09, 0xe1, 0xa2, 0xb6, 0x6c, 0x9e, 0x1d, 0x89, 0x70, 0x70, 0x1f,
	0x2c, 0x02, 0x90, 0xbd, 0xc1, 0xe2, 0x6f, 0x19, 0x7f, 0x82, 0x89, 0x2b, 0xe4, 0xe7, 0xff, 0x63,
	0x43, 0xe2, 0xc9, 0xc5, 0x1e, 0xca, 0x5b, 0xdd, 0x8c, 0x9e, 0x99, 0xa9, 0xaa, 0x89, 0x3d, 0xd2,
	0xd5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x21, 0x50, 0x9e, 0x6e, 0x03, 0x02, 0x00, 0x00,
}
