// Code generated by protoc-gen-twirp v5.5.0, DO NOT EDIT.
// source: user.proto

package pb

import bytes "bytes"
import strings "strings"
import context "context"
import fmt "fmt"
import ioutil "io/ioutil"
import http "net/http"

import jsonpb "github.com/golang/protobuf/jsonpb"
import proto "github.com/golang/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// =====================
// UserService Interface
// =====================

type UserService interface {
	// ユーザー登録
	Register(context.Context, *UserServiceRegisterRequest) (*UserServiceRegisterResponse, error)

	// プロフィール更新
	UpdateProfile(context.Context, *UserServiceUpdateProfileRequest) (*UserServiceUpdateProfileResponse, error)
}

// ===========================
// UserService Protobuf Client
// ===========================

type userServiceProtobufClient struct {
	client HTTPClient
	urls   [2]string
}

// NewUserServiceProtobufClient creates a Protobuf client that implements the UserService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewUserServiceProtobufClient(addr string, client HTTPClient) UserService {
	prefix := urlBase(addr) + UserServicePathPrefix
	urls := [2]string{
		prefix + "Register",
		prefix + "UpdateProfile",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &userServiceProtobufClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &userServiceProtobufClient{
		client: client,
		urls:   urls,
	}
}

func (c *userServiceProtobufClient) Register(ctx context.Context, in *UserServiceRegisterRequest) (*UserServiceRegisterResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "article")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "Register")
	out := new(UserServiceRegisterResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[0], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceProtobufClient) UpdateProfile(ctx context.Context, in *UserServiceUpdateProfileRequest) (*UserServiceUpdateProfileResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "article")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "UpdateProfile")
	out := new(UserServiceUpdateProfileResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[1], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// =======================
// UserService JSON Client
// =======================

type userServiceJSONClient struct {
	client HTTPClient
	urls   [2]string
}

// NewUserServiceJSONClient creates a JSON client that implements the UserService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewUserServiceJSONClient(addr string, client HTTPClient) UserService {
	prefix := urlBase(addr) + UserServicePathPrefix
	urls := [2]string{
		prefix + "Register",
		prefix + "UpdateProfile",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &userServiceJSONClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &userServiceJSONClient{
		client: client,
		urls:   urls,
	}
}

func (c *userServiceJSONClient) Register(ctx context.Context, in *UserServiceRegisterRequest) (*UserServiceRegisterResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "article")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "Register")
	out := new(UserServiceRegisterResponse)
	err := doJSONRequest(ctx, c.client, c.urls[0], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceJSONClient) UpdateProfile(ctx context.Context, in *UserServiceUpdateProfileRequest) (*UserServiceUpdateProfileResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "article")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "UpdateProfile")
	out := new(UserServiceUpdateProfileResponse)
	err := doJSONRequest(ctx, c.client, c.urls[1], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ==========================
// UserService Server Handler
// ==========================

type userServiceServer struct {
	UserService
	hooks *twirp.ServerHooks
}

func NewUserServiceServer(svc UserService, hooks *twirp.ServerHooks) TwirpServer {
	return &userServiceServer{
		UserService: svc,
		hooks:       hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *userServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// UserServicePathPrefix is used for all URL paths on a twirp UserService server.
// Requests are always: POST UserServicePathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const UserServicePathPrefix = "/twirp/article.UserService/"

func (s *userServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "article")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/article.UserService/Register":
		s.serveRegister(ctx, resp, req)
		return
	case "/twirp/article.UserService/UpdateProfile":
		s.serveUpdateProfile(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *userServiceServer) serveRegister(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveRegisterJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveRegisterProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *userServiceServer) serveRegisterJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Register")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(UserServiceRegisterRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *UserServiceRegisterResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.UserService.Register(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *UserServiceRegisterResponse and nil error while calling Register. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveRegisterProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Register")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(UserServiceRegisterRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *UserServiceRegisterResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.UserService.Register(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *UserServiceRegisterResponse and nil error while calling Register. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveUpdateProfile(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveUpdateProfileJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveUpdateProfileProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *userServiceServer) serveUpdateProfileJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UpdateProfile")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(UserServiceUpdateProfileRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *UserServiceUpdateProfileResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.UserService.UpdateProfile(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *UserServiceUpdateProfileResponse and nil error while calling UpdateProfile. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveUpdateProfileProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UpdateProfile")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(UserServiceUpdateProfileRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *UserServiceUpdateProfileResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.UserService.UpdateProfile(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *UserServiceUpdateProfileResponse and nil error while calling UpdateProfile. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor1, 0
}

func (s *userServiceServer) ProtocGenTwirpVersion() string {
	return "v5.5.0"
}

var twirpFileDescriptor1 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x95, 0x34, 0xa2, 0xf4, 0xaa, 0xa2, 0xea, 0xa6, 0x2a, 0x80, 0x1a, 0x05, 0x86, 0xc2,
	0x90, 0x4a, 0x65, 0x62, 0x2c, 0x4f, 0x00, 0x86, 0x2e, 0x2c, 0x28, 0x4d, 0xae, 0x91, 0xa5, 0xb6,
	0x36, 0xb6, 0xc3, 0xb3, 0xf1, 0x0c, 0x3c, 0x15, 0xaa, 0x1d, 0xa3, 0x22, 0xa5, 0xc0, 0xc0, 0x66,
	0x9d, 0xbf, 0xbb, 0xff, 0xcb, 0xc5, 0x00, 0xb5, 0x26, 0x95, 0x49, 0x25, 0x8c, 0xc0, 0x6e, 0xae,
	0x0c, 0x2f, 0xd6, 0x14, 0x8f, 0x2b, 0x21, 0xaa, 0x35, 0x4d, 0x6d, 0x79, 0x59, 0xaf, 0xa6, 0x86,
	0x6f, 0x48, 0x9b, 0x7c, 0x23, 0x1d, 0x99, 0xbe, 0x07, 0x10, 0x2d, 0x34, 0x29, 0x3c, 0x81, 0x90,
	0x97, 0xa3, 0x20, 0x09, 0x26, 0x3d, 0x16, 0xf2, 0x12, 0xaf, 0xa1, 0x2b, 0x95, 0x58, 0xf1, 0x35,
	0x8d, 0xc2, 0x24, 0x98, 0xf4, 0x67, 0xc3, 0xac, 0x19, 0x9a, 0xdd, 0xbb, 0x3a, 0xf3, 0x00, 0xde,
	0x02, 0x14, 0x8a, 0x72, 0x43, 0xe5, 0x4b, 0x6e, 0x46, 0x1d, 0x8b, 0xc7, 0x99, 0x8b, 0xce, 0x7c,
	0x74, 0xf6, 0xe4, 0xa3, 0x59, 0xaf, 0xa1, 0xe7, 0x66, 0xd7, 0x5a, 0xcb, 0xd2, 0xb7, 0x46, 0xbf,
	0xb7, 0x36, 0xf4, 0xdc, 0xa4, 0x0f, 0xd0, 0x6d, 0x4c, 0x10, 0x21, 0xda, 0xe6, 0x1b, 0x6a, 0xf4,
	0xed, 0x19, 0x87, 0xd0, 0xc9, 0x2b, 0x27, 0x3f, 0x60, 0xbb, 0x23, 0x26, 0xd0, 0x2f, 0x49, 0x17,
	0x8a, 0x4b, 0xc3, 0xc5, 0xd6, 0x7a, 0xf6, 0xd8, 0x7e, 0x29, 0x3d, 0x83, 0x78, 0xb7, 0x8c, 0x47,
	0x52, 0x6f, 0xbc, 0x20, 0x46, 0x15, 0xd7, 0x86, 0x14, 0xa3, 0xd7, 0x9a, 0xb4, 0x49, 0xcf, 0xe1,
	0xb4, 0xf5, 0x56, 0x4b, 0xb1, 0xd5, 0x94, 0x72, 0x18, 0xef, 0x5d, 0x2f, 0xac, 0xa7, 0x5f, 0x95,
	0x9b, 0xf0, 0x6f, 0x9e, 0x29, 0x24, 0x87, 0xa3, 0x9c, 0xce, 0xec, 0x23, 0x80, 0xfe, 0x1e, 0x84,
	0x0b, 0x38, 0xf6, 0xca, 0x78, 0xf1, 0xf5, 0x2f, 0x0f, 0x7f, 0x6e, 0x7c, 0xf9, 0x33, 0xe4, 0x62,
	0xb0, 0x84, 0xc1, 0xb7, 0x7c, 0x9c, 0xb4, 0xb5, 0xb5, 0x6d, 0x23, 0xbe, 0xfa, 0x03, 0xe9, 0x52,
	0xee, 0xa2, 0xe7, 0x50, 0x2e, 0x97, 0x47, 0xf6, 0x41, 0xdc, 0x7c, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x82, 0x98, 0xf3, 0x18, 0xeb, 0x02, 0x00, 0x00,
}
