// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	article2 "github.com/inari111/layered-architecture-study/application/article"
	"github.com/inari111/layered-architecture-study/domain"
	"github.com/inari111/layered-architecture-study/handler/api"
	"github.com/inari111/layered-architecture-study/infra/persistence/article"
	"net/http"
)

// Injectors from api.go:

func InitializeAPIHandler() http.Handler {
	repository := article.NewRepository()
	currentTimeFunc := domain.NewCurrentTimeFunc()
	application := article2.NewApplication(repository, currentTimeFunc)
	articleService := api.NewArticleService(application)
	handler := api.NewHandler(articleService)
	return handler
}
